project:
  type: book

book:
  title: "A practical guide to ecological forecasting in R"
  author:
    - name: "R. Quinn Thomas"
      orcid: 0000-0003-1282-7825
      email: rqthomas@vt.edu
      url: https://rquinnthomas.com
      affiliation:
        - Co-director of Virginia Tech Center for Ecosystem Forecasting
        - Department of Forest Resources and Environmental Conservation
        - Department of Biological Sciences
        - Virginia Tech
  date: today
  date-format: long
  license: "CC BY-NC"
  chapters:
    - index.qmd
    - intro.qmd
    - background-skills.qmd
    - part: setting-the-stage.qmd
      chapters:
        - intro-ecoforecast.qmd
        - first-forecast.qmd
        - understand-uncertainty.qmd
        - second-forecast.qmd
        - using-data.qmd
        - third-forecast.qmd
        - decision-making.qmd
        - visualizing.qmd
    - part: "Project 1"
      chapters:
        - project1.qmd
    - part: advanced-forecasting.qmd
      chapters:
        - process-model.qmd
        - prop-uncertainty.qmd
        - neon-data.qmd
        - parameter-calibration1.qmd
        - parameter-calibration2.qmd
        - parameter-calibration3.qmd
        - particle-filter.qmd
        - particle-filter2.qmd
        - pulling-together.qmd
    - part: "Project 2"
      chapters:
        - project2.qmd
    - summary.qmd
    - references.qmd
    - part: "Appendix"
      chapters:
      - weather-drivers.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

