project:
  type: book

book:
  title: "Ecological Modeling and Forecasting"
  author: "R. Quinn Thomas"
  date: "12/5/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - setting-the-stage.qmd
    - process-model.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

