project:
  type: book

book:
  title: "Ecological Modeling and Forecasting"
  author: "R. Quinn Thomas"
  date: "12/5/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - background-skills.qmd
    - part: setting-the-stage.qmd
      chapters:
        - intro-ecoforecast.qmd
        - first-forecast.qmd
        - understand-uncertainty.qmd
        - second-forecast.qmd
        - using-data.qmd
        - third-forecast.qmd
        - decision-making.qmd
        - visualizing.qmd
    - part: project1.qmd
      chapters:
        - modeling-approaches.qmd
        - submitting-forecasts.qmd
    - part: advanced-forecasting.qmd
      chapters:
        - process-model.qmd
        - prop-uncertainty.qmd
        - neon-data.qmd
        - parameter-calibration1.qmd
        - parameter-calibration2.qmd
        - parameter-calibration3.qmd
        - particle-filter.qmd
        - pulling-together.qmd
    - part: project2.qmd
      chapters:
        - project2-details.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

