project:
  type: book

book:
  title: "A practical guide to ecological forecasting"
  author: "R. Quinn Thomas"
  date: "12/5/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - background-skills.qmd
    - part: setting-the-stage.qmd
      chapters:
        - intro-ecoforecast.qmd
        - first-forecast.qmd
        - understand-uncertainty.qmd
        - second-forecast.qmd
        - using-data.qmd
        - third-forecast.qmd
        - decision-making.qmd
        - visualizing.qmd
    - part: "Project 1"
      chapters:
        - project1.qmd
    - part: advanced-forecasting.qmd
      chapters:
        - process-model.qmd
        - prop-uncertainty.qmd
        - parameter-calibration1.qmd
        - parameter-calibration2.qmd
        - parameter-calibration3.qmd
        - particle-filter.qmd
        - pulling-together.qmd
    - part: "Project 2"
      chapters:
        - project2.qmd
    - summary.qmd
    - references.qmd
    - part: "Appendix"
      chapters:
      - neon-data.qmd
      - weather-drivers.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

